### ISSUE TITLE
Are dots in geoip_lookup_key supported?

### ISSUE THREAD

**Issue by 6A63** [y-ken/fluent-plugin-geoip#14]
Getting nil output on geo keys when I try to use key names containing dots for `geoip_lookup_key`.  Example:

> type geoip
> geoip_lookup_key 'ip.addr_src', 'ip.addr_dst'
>  <record>
>    orig_country  ${country_code['ip.addr_src']}
>    resp_country  ${country_code['ip.addr_dst']}
>    orig_location ${latitude['ip.addr_src']},${longitude['ip.addr_src']}
>    resp_location ${latitude['ip.addr_dst']},${longitude['ip.addr_dst']}
>  </record>

I get the following:

`{ orig_country":null,"resp_country":null,"orig_location":",","resp_location":","}`

**Comment by ebuildy** [comment]
Hello, I can confirm this is working like a charm!

Thanks you,
