### ISSUE TITLE
Implementing a filter plugin support

### ISSUE THREAD

**Issue by kiyoto** [y-ken/fluent-plugin-geoip#17]
This plugin is an example of a useful output plugin that should really be a filter plugin (in the new Fluentd versions that support filter plugins). I suggest that
1. the GeoIP lookup is factored out into a separate module/library
2. Both the existing output plugin and the filter plugin (to be implemented) use 1.
3. Encourage the users to use the filter plugin version =)

**Comment by okkez** [comment]
I'm trying to implement this.
https://github.com/okkez/fluent-plugin-geoip/tree/add-filter-plugin

**Comment by repeatedly** [comment]
:+1:

**Comment by salekseev** [comment]
:+1:

**Comment by kiyoto** [comment]
Any decision on this one? @okkez and @y-ken?

**Comment by okkez** [comment]
@kiyoto I'm waiting for @y-ken .

**Comment by okkez** [comment]
Already supported.
