### ISSUE TITLE
postal code

### ISSUE THREAD

**Issue by WillPlatnick** [y-ken/fluent-plugin-geoip#25]
Is there a reason that postal code isn't implemented? Open to a PR if not?

**Comment by y-ken** [comment]
Hi @WillPlatnick 
It is welcome to pull-request!
There are no reason for postal code hasn't implemented now.
It might be supported that 'geoip-c' gem which using from this plugin.
https://github.com/mtodd/geoip

**Comment by okkez** [comment]
postal code is supported with GeoIP2.
