### ISSUE TITLE
'skip_adding_null_record  true' doesn't seem to work when a contry code is 'A1'

### ISSUE THREAD

**Issue by lunardial** [y-ken/fluent-plugin-geoip#26]
I'm using fluent-plugin-geoip (0.5.1) and adding location_array.
If country codes are 'JP', 'CN', 'US', well working.
But a country code is 'A1', my location_array is following although I use 'skip_adding_null_record  true'.
  "location_array":[null,null]

**Comment by y-ken** [comment]
Hi @lunardial 
Thank for your report!
I'll consider the case of missing location like below.

* A1,"Anonymous Proxy"
* A2,"Satellite Provider"

**Comment by juntagabor** [comment]
Happens to me too:
geoiplookup returns:
GeoIP Country Edition: US, United States
GeoIP City Edition, Rev 1: US, AE, Armed Forces Europe, Middle East, & Canada, Apo, N/A, 0.000000, 0.000000, 0, 323
GeoIP Organization Edition: Nass Al Iraq Company for General Trading and Techn

I am getting:
	"geoip_city": "Apo",
	"geoip_country_code": "US",
	"geoip_country_name": "United States",
	"geoip_region": "AE",
	"location_array": [null, null],

with the following config:
...
  <record>
    geoip_city                  ${city["remote_addr"]}
    geoip_country_code          ${country_code["remote_addr"]}
    geoip_country_name          ${country_name["remote_addr"]}
    geoip_region                ${region["remote_addr"]}
    location_array              '[${longitude["remote_addr"]},${latitude["remote_addr"]}]'
  </record>
  skip_adding_null_record  true
...

**Comment by y-ken** [comment]
Thank you for reporting with details.

**Comment by y-ken** [comment]
Hi @lunardial , @juntagabor 
I get it what happen for you.
Would you please give me the any samples of ip address to test?

**Comment by juntagabor** [comment]
Thank you @y-ken ... the IP I noticed this issue with, is 185.104.157.241

**Comment by lam-juice** [comment]
I believe "skip_adding_null_record" should be designed with a list of keys, instead of just a true/false.
With true/false the plugin checks for the first value, and skips adding the entire record if the first value is missing (so a missing lat/long while the city is present can still add a [null,null] to the record), a list of keys would allow skipping only the lat/long, when, e.g. the lat/long is missing, while keeping city/region.

**Comment by y-ken** [comment]
@lam-juice 

Would you please reorder the configuration lat,lon is first and city and region is last?
I see It have to fix it.

**Comment by okkez** [comment]
No response.
Please reopen this issue, if someone encounter same issue.
