### ISSUE TITLE
IP with no city field in the database ignored under certain circumstances

### ISSUE THREAD

**Issue by mparienti** [y-ken/fluent-plugin-geoip#27]
When you put `city` in the first position in the record configuration, as it is in the `README.md` file, or as:

```
  <record>
    city            ${city["host"]}
    latitude        ${latitude["host"]}
    …
```

then all IP who don’t geolocate with a city in the GeoIP database are ignored. They are not geo-localized at all. Even if these IP have a country, a latitude and longitude in the database, no field are added from the geolocate result.

The solution is to remove the line `city    ${city["host"]}` from the first position, and put it at the second or at the last position. For example :

```
  <record>
    latitude        ${latitude["host"]}
    city            ${city["host"]}
    …
```

Then (almost) all your IP are geo-localized.

Would you look like a PR with a modified `README.md` file to help future users of the plugin?

**Comment by y-ken** [comment]
Hi @mparienti 
Thank you for comment. I'll check the detail tomorrow.

**Comment by y-ken** [comment]
I found the reason for this behavior.
It is skipping when first element are null record.
To fix this issue, Reorder the `@geoip_lookup_key` element or check with another field to skip.

**Comment by mparienti** [comment]
Should not the program avoid this behavior?

Or at least users should be informed about it, from the `README.md`.

**Comment by y-ken** [comment]
Yes. For now, Updated the README.
And I'm going to fix the unexpected behavior soon.

Would you please give me the sample of IP which caused the error?

**Comment by okkez** [comment]
This issue is already resolved maybe.
If someone encounter this issue, please open new issue and refer to this issue.
