### ISSUE TITLE
Visualization on kibana

### ISSUE THREAD

**Issue by enod** [y-ken/fluent-plugin-geoip#28]
Hi there,
I've successfully added geoip fields using your guide. But when I try to visualize, It gives me following error : 
<img width="352" alt="screen shot 2016-01-05 at 5 03 10 pm" src="https://cloud.githubusercontent.com/assets/6023883/12111229/bb82ae54-b3ce-11e5-990c-170968d70239.png">

Does that mean I should add another field called geo_point? if so how can I do that using your plugin?

 Thanks.

**Comment by ebuildy** [comment]
Looks like your elasticsearch index mapping does not contain a geo_point field:

https://www.elastic.co/guide/en/elasticsearch/reference/1.7/mapping-geo-point-type.html

Check that!

**Comment by okkez** [comment]
no response.
