### ISSUE TITLE
messes up extra fields if match found

### ISSUE THREAD

**Issue by JoeOrtiz** [y-ken/fluent-plugin-geoip#41]
I've seen that if a match is found with the geoip filter, or even from match. It truncates or doesn't properly submit extra fields properly.

Like I have a payload field, if no match found from geoip, it shows up fine like so:

`<?xml version="1.0"?> <!DOCTYPE pdf PUBLIC "-//big.faceless.org//report" "report-1.1.dtd"><pdf lang="en_US"> <body> This is a test of the PDF generator. </body> </pdf>`

Now if it does match with geoip, the same payload field it just submits as:

`<?xml version="1.0"?>`

I am not too sure why it would mess up other fields in the document, but somehow after it passes through and has a match it does weird things with the other fields.

**Comment by okkez** [comment]
Please reopen this issue, when someone encounter same issue.
