### ISSUE TITLE
Incorrect output and blank geoip_point

### ISSUE THREAD

**Issue by Kumaravel2904** [y-ken/fluent-plugin-geoip#45]
I have noticed that this plugin is providing incorrect data for some of the requested IP address.
I am using this plugin with the following config in the Fluentd
```
  @type geoip
  geoip_lookup_key firstPublicIP
  <record>
    geoip_city       ${city["firstPublicIP"]}
    geoip_country3   ${country_code3["firstPublicIP"]}
    geoip_country    ${country_code["firstPublicIP"]}
    geoip_name       ${country_name["firstPublicIP"]}
    geoip_region     ${region["firstPublicIP"]}
    geoip_point      ${latitude["firstPublicIP"]},${longitude["firstPublicIP"]}
  </record>
```

The lookup key value is 180.94.85.84 for which I get an out as 
**_"geoip_city":"Apo","geoip_country3":"USA","geoip_country":"US","geoip_name":"United States","geoip_region":"AE","geoip_point":","_**
Because of this the entire record is being rejected as there is schema for the geoip_point.
Also the output seems to be incorrect as I tried the same IP in the website https://www.maxmind.com/en/geoip-demo and got different output.

Please suggest and thanks in advance.

Regards,
Kumaravel

**Comment by y-ken** [comment]
Hi @Kumaravel2904 
Bundled geoip lite city database is free edition which are limited accuracy.
You can get same result when use specify purchased geoip city database.
https://www.maxmind.com/en/geoip2-city

**Comment by y-ken** [comment]
Do you have any problem when you get blank geoip_point?
Is it better to set null?

**Comment by Kumaravel2904** [comment]
The problem is that the entire message is rejected by the ElasticSearch because the geoip_point excepted as "34.43,23.34" but get it as "," thus giving an exception and loss of message.
Can please help me out how I can set the value to some default value like "0,0" in such cases so that atleast I have no data loss.

**Comment by y-ken** [comment]
@okkez 
I'd like to change behavior if it couldn't detect geo locate.
I guess current behavior results only comma `,` with this configuration.
geoip_point      ${latitude["firstPublicIP"]},${longitude["firstPublicIP"]}

How do you think set 0.0 instead of nil when latitude and longitude has no data?

**Comment by Kumaravel2904** [comment]
I have just added a check for blank records and in such case modify the value to 0,0 using the record_transformer

geoip_point ${(record["geoip_point"]==","||!record["geoip_point"]) ? "0,0":record["geoip_point"]}

**Comment by y-ken** [comment]
thank you for showing the workarounds.
I think it is potential trap which might be care not to cause error.

**Comment by okkez** [comment]
@y-ken Do you want to set default value to all field type?
It is difficult to define default value to all field type. Because all IP address don't have same field type.

**Comment by y-ken** [comment]
I suggest It overrides only for lat and lon and set default value.

**Comment by okkez** [comment]
It's ok to me. I will consider to implement the default value feature later.

**Comment by y-ken** [comment]
Thank you.
Would you please this enhancement for fluentd v0.12 as fluent-plugin-geoip v0.8.1 and also back port to v1.0.x?

**Comment by okkez** [comment]
BTW,   GeoLite2-City.mmdb will return ``(lat, lon) = (33.0, 66.0)`` for  "180.94.85.84".
