### ISSUE TITLE
GeoLite City Database

### ISSUE THREAD

**Issue by discostur** [y-ken/fluent-plugin-geoip#47]
Hi,

i just downloaded the newest GeoLite City Database form maxmind 

https://dev.maxmind.com/geoip/geoip2/geolite2/

but fluentd-plugin-geoip recognizes it as Country Edition:

```
Invalid database type GeoIP Country Edition, expected GeoIP City Edition, Rev 1
```

Just downloaded it two times, always getting the same error. Any Ideas?

Thanks

**Comment by okkez** [comment]
fluent-plugin-geoip v1.0.0 support GeoIP2 database, but old version of fluent-plugin-geoip does not support GeoIP2 database by default.
Current version of fluent-plugin-geoip v1.0.0/v0.8.0 bundles latest GeoIP2 database.
