### ISSUE TITLE
ASN info in geoip plugin

### ISSUE THREAD

**Issue by vishnubraj** [y-ken/fluent-plugin-geoip#48]
Hi,

Can i get the BGP ASN info(Autonomous System Number) of specific IP address using this plugin?

**Comment by okkez** [comment]
Yes, use database included ASN information.
 For example, GeoLite2 ASN. For more details, see http://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by y-ken** [comment]
We need to accept asn keys in code
https://github.com/y-ken/fluent-plugin-geoip/blob/master/lib/fluent/plugin/geoip.rb#L21

**Comment by okkez** [comment]
geoip2_c backend support all keys.

**Comment by y-ken** [comment]
Oh, I see!
It need list up the supported geoip database types in README.
Does it support `GeoLite2 Country` and `GeoLite2 ASN` not only `GeoLite2 City`?

**Comment by okkez** [comment]
> Does it support GeoLite2 Country and GeoLite2 ASN not only GeoLite2 City?

Maybe, yes. For more details, see https://github.com/okkez/geoip2_c/tree/master/test
geoip2_c satisfies MaxMind-DB spec.

**Comment by okkez** [comment]
No response. Closed.
