### ISSUE TITLE
Drop out_geoip

### ISSUE THREAD

**Issue by okkez** [y-ken/fluent-plugin-geoip#69]
filter_geoip is enough to add geoip related data to records.
There are no out_geoip specific features except tag rewriting, tag rewriting is not recommended by Fluentd core developers.
Users can rewrite tag using fluent-plugin-rewrite-tag-filter (combo with filter_geoip).

Therefore I think it is time to remove out_geoip.

@y-ken How do you think about this?

**Comment by y-ken** [comment]
Thank you. I'm very agree to drop that.

**Comment by okkez** [comment]
Thanks!
