### ISSUE TITLE
GeoIp filter returns null

### ISSUE THREAD

**Issue by JacobHeidelbach** [y-ken/fluent-plugin-geoip#71]
#### Problem
Hi

I'm trying to utilize the geoip filter in fluentd, but for some reason I cant make it return any values.

My config is like below, and my FluentD has a field called "host" with a valid IP-address.

No errors are rendered in my fluentd log - any help appreciated.

Best regards
Jacob

```
<filter kubernetes.**>
      @type geoip

      # Specify one or more geoip lookup field which has ip address (default: host)
      # in the case of accessing nested value, delimit keys by dot like 'host.ip'.
      geoip_lookup_keys  host

      # Specify optional geoip database (using bundled GeoLiteCity databse by default)
      # geoip_database    "/path/to/your/GeoIPCity.dat"
      # Specify optional geoip2 database (using bundled GeoLite2 database by default)
      # geoip2_database   "/path/to/your/GeoLite2-City.mmdb"
      # Specify backend library (geoip2_c, geoip, geoip2_compat)
      backend_library geoip2_c

      # Set adding field with placeholder (more than one settings are required.)
      <record>
        city            ${city.names.en['host']}
        latitude        ${location.latitude['host']}
        longitude       ${location.longitude['host']}
        country         ${country.iso_code['host']}
        country_name    ${country.names.en['host']}
        postal_code     ${postal.code['host']}
        region_code     ${subdivisions.0.iso_code['host']}
        region_name     ${subdivisions.0.names.en['host']}
      </record>
      # To avoid get stacktrace error with `[null, null]` array for elasticsearch.
      skip_adding_null_record  false
      # Set @log_level (default: warn)
      @log_level         debug
    </filter>
```
...

#### Steps to replicate

Provide example config and message

#### Expected Behavior
Expecting my record-fields to be filled out and not be null.
...

#### Your environment

* Debian GNU/Linux 9 \n \l
* root@fluentd-logzio-v1:/# fluentd --version
   fluentd 1.1.0
* plugin version
  * paste boot log of fluentd or td-agent
  *root@fluentd-logzio-v1:/# fluent-gem list

*** LOCAL GEMS ***

activesupport (5.1.5)
addressable (2.5.2)
bigdecimal (1.2.8)
concurrent-ruby (1.0.5)
cool.io (1.5.3)
did_you_mean (1.0.0)
dig_rb (1.0.1)
domain_name (0.5.20170404)
ffi (1.9.23)
fluent-plugin-detect-exceptions (0.0.9)
fluent-plugin-geoip (1.2.0)
fluent-plugin-kubernetes_metadata_filter (1.0.1)
fluent-plugin-logzio (0.0.16)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-prometheus (0.3.0)
fluent-plugin-systemd (0.3.1)
fluentd (1.1.0)
geoip-c (0.9.1)
geoip2_c (0.3.2)
http (0.9.8)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
i18n (0.9.5)
io-console (0.4.5)
json (1.8.3)
kubeclient (1.1.4)
lru_redux (1.1.0)
mime-types (3.1)
mime-types-data (3.2016.0521)
minitest (5.11.3, 5.9.0)
msgpack (1.2.4)
net-http-persistent (2.9.4)
net-telnet (0.1.1)
netrc (0.11.0)
oj (3.3.1)
power_assert (0.2.7)
prometheus-client (0.7.1)
psych (2.1.0)
public_suffix (3.0.2)
quantile (0.2.0)
rake (10.5.0)
rdoc (4.2.1)
recursive-open-struct (1.0.0)
rest-client (2.0.2)
serverengine (2.0.6)
sigdump (0.2.4)
strptime (0.2.3)
systemd-journal (1.3.1)
test-unit (3.1.7)
thread_safe (0.3.6)
tzinfo (1.2.5)
tzinfo-data (1.2018.3)
unf (0.1.4)
unf_ext (0.0.7.5)
yajl-ruby (1.3.1)

**Comment by okkez** [comment]
Could you show me **full** configuration and your logs processed by fluentd?
Could you check IP addresses in logs using [utils/dump.rb](https://github.com/y-ken/fluent-plugin-geoip/blob/master/utils/dump.rb) like below?

```
$ git clone https://github.com/y-ken/fluent-plugin-geoip
$ cd fluent-plugin-geoip
$ bundle install
$ bundle exec ruby utils/dump.rb geoip2 <IP address>
```

**Comment by JacobHeidelbach** [comment]
Hi @okkez 
Thanks for the feedback - took me some time to make my local dev machine run above code (didn't succeed as Ruby/Bundle made a mess of the deps.)
Ended up running in a docker container, and interestingly enough the result of the exec is:
`root@746d28771096:/home/test/fluent-plugin-geoip# bundle exec ruby utils/dump.rb geoip2 100.96.8.1
{}`

**Comment by okkez** [comment]
`100.96.8.1` may be private address in https://ipinfo.io/bogon

```
$ ruby -ripaddr -e "p IPAddr.new('100.64.0.0/10').include?('100.96.8.1')"
true
```

See also `whois 100.96.8.1`.

**Comment by JacobHeidelbach** [comment]
The application creating log-entries is sitting behind an Amazon Elastic Load Balancer, and I wasn't aware that it stripped away the IP of the client to replace it with an IP which isn't resolvable.
Thanks a lot for the help :)
