### ISSUE TITLE
Partial nested value lookup key

### ISSUE THREAD

**Issue by Xyaren** [y-ken/fluent-plugin-geoip#75]
#### Problem

geoip_lookup_keys fails with complex json:

Config:
```
geoip_lookup_keys mdc.req.realIp
```

Json:
```
{
  "mdc": {
      "req.realIp": "1.2.3.4",
    }
}
```

#### Expected Behavior

Resolves the key correctly.

**Comment by okkez** [comment]
Please try #72

**Comment by okkez** [comment]
@Xyaren ping?

**Comment by Xyaren** [comment]
Sorry for the delay. To speed things up I modified the data before sending it into fluentd. 

I did not test the method you provided sorry.

**Comment by okkez** [comment]
OK, thank you for reply.
