### ISSUE TITLE
 geoip_lookup_key or  geoip_lookup_keys?

### ISSUE THREAD

**Issue by khteh** [y-ken/fluent-plugin-geoip#79]
#### Problem
According to https://docs.fluentd.org/v1.0/articles/filter_geoip, it is  geoip_lookup_key but the readme here suggests  geoip_lookup_keys..?

**Comment by okkez** [comment]
Thank you for reporting the issue. Please use `geoip_lookup_keys` because `geoip_lookup_key` has been deprecated.

**Comment by okkez** [comment]
Closing.

**Comment by khteh** [comment]
geoip_lookup_keyS suggests a LIST. Why is it plural and how to use it?

**Comment by okkez** [comment]
Please check README.md https://github.com/y-ken/fluent-plugin-geoip#tips-how-to-geolocate-multiple-key
