### ISSUE TITLE
tomcat  geoip_lookup_key 

### ISSUE THREAD

**Issue by khteh** [y-ken/fluent-plugin-geoip#80]
#### Problem
tomcat access logs geoip_lookup_key field "host" is missing. Here is my log captured in Kibana:

{
  "_index": "iconverse.access.logs-2019.02.10",
  "_type": "fluentd",
  "_id": "H5V-1mgB1rnHQmWDBv0E",
  "_version": 1,
  "_score": null,
  "_source": {
    "message": "219.74.35.66 - - [10/Feb/2019:08:19:41 +0000] \"POST /myendpoint HTTP/1.1\" 200 36",
    "country_code": null,
    "country_name": null,
    "@timestamp": "2019-02-10T08:19:45.056608782+00:00"
  },
  "fields": {
    "@timestamp": [
      "2019-02-10T08:19:45.056Z"
    ]
  },
  "sort": [
    1549786785056
  ]
}

I have multiple filters on td-agent3 config as I don't know which one works. The one which captures the log above is:

    <filter iconverse-access>
      @type geoip
      geoip_lookup_key      host
      backend_library geoip2_c
      <record>
        country_code ${country.iso_code["host"]}
        country_name ${country.names.en["host"]}
      </record>
    </filter>

As you can see, the country_code and name are null in Kibana. There is IP in the tomcat log which appears in "message" field.
Any advice and insight is appreciated. Thanks.

**Comment by okkez** [comment]
Parse your logs first using [the built-in filter_parser plugin](https://docs.fluentd.org/v1.0/articles/filter_parser).

You can use [the built-in parser_regexp plugin](https://docs.fluentd.org/v1.0/categories/parser_regexp) or [parser_grok plugin](https://github.com/fluent/fluent-plugin-grok-parser) to parse your message field.

```
<filter iconverse-access>
  @type parse
  key_name message
  reserve_data true
  reserve_time true
  <parse>
    @type grok
    pattern %{IP:host:string} %{GREEDYDATA:rest:string}
  </parse>
</filter>

<filter iconverse-access>
  @type geoip
  geoip_lookup_key      host
  backend_library geoip2_c
  <record>
    country_code ${country.iso_code["host"]}
    country_name ${country.names.en["host"]}
  </record>
</filter>
```
